---
title: "Fig Tree"
author: "Zachary Halvorson"
date: "7/20/2019"
output: html_document
---

```{r, setup, echo = FALSE, warning = FALSE, message = FALSE}

library(tidyverse)
library(tidyr)
library(lubridate)
library(reshape2)

```

```{r, fig_data, echo = FALSE, warning = FALSE}

figs_2017 <- read.csv(file = "data/2017figs.csv", header = TRUE, sep = ",", fileEncoding="UTF-8-BOM", stringsAsFactors = FALSE)
figs_2018 <- read.csv(file = "data/2018figs.csv", header = TRUE, sep = ",", fileEncoding="UTF-8-BOM", stringsAsFactors = FALSE)
figs_2019 <- read.csv(file = "data/2019figs.csv", header = TRUE, sep = ",", fileEncoding="UTF-8-BOM", stringsAsFactors = FALSE)

figs_2017$Day <- mdy(figs_2017$Day)
figs_2018$Day <- mdy(figs_2018$Day)
figs_2019$Day <- mdy_hm(figs_2019$Day) %>% with_tz("US/Pacific")

figs_2017 <- figs_2017 %>% complete(Day = seq.Date(min(Day), max(Day), by="day"))
figs_2018 <- figs_2018 %>% complete(Day = seq.Date(min(Day), max(Day), by="day"))
#figs_2019 <- figs_2019 %>% complete(Day = seq.Date(min(Day), max(Day), by="day"))


figs_all <- read.csv(file = "data/allfigs.csv", header = TRUE, sep = ",", fileEncoding="UTF-8-BOM", stringsAsFactors = FALSE)

figs_all$Day <- mdy(figs_all$Day)

figs_all <- figs_all %>% complete(Day = seq.Date(min(Day), max(Day), by="day"))


```

```{r, weather_data, echo = FALSE, warning = FALSE}


weather_data <- read.csv(file = "data/weather.csv", header = TRUE, sep = ",", fileEncoding = "UTF-8-BOM", stringsAsFactors = FALSE)

#Next we split the weather data into the daily summary and hourly values based on the station number
daily_weather <- weather_data %>% filter(SOURCE == 6) %>% filter(Rain != "T" & Rain != "0")  
hourly_weather <- weather_data %>% filter(SOURCE == 7)

#split the date string at the T value for a delimiter and keep whats before for the daily dataset

for (i in 1:nrow(daily_weather)){
  daily_weather$Day[i] <- format(as.Date(strsplit(as.character(daily_weather$Day[i]), "T")[[1]][1]), '%m/%d/%Y')
}

daily_weather$Day <- mdy(daily_weather$Day)

daily_weather$Rain[daily_weather$Rain == ""] <- 0


```


```{r, solar_data, echo = FALSE, warning = FALSE}

#For the solar data, we delete every other row as it is empty in the csv file

solar_data <- as_tibble(read.csv(file = "data/solarday.csv", header = TRUE, sep = ",", fileEncoding = "UTF-8-BOM", stringsAsFactors = FALSE))

delete <- seq(1, length(solar_data$Day), 2)
solar_data <- solar_data[-delete, ]

solar_data$Day <- mdy(solar_data$Day)


```

```{r, rain_data, echo = FALSE, warning = FALSE}

#Extract rain data from daily weather and then drop from original data set
rain_days <- daily_weather %>% filter(Rain != "0") %>% select(Day, Rain)
rain_days$Rain <- as.numeric(rain_days$Rain)
daily_weather$Rain <- NULL

```

```{r, temperature_data, echo = FALSE, warning = FALSE}

temperature_data <- as_tibble(read.csv(file = "data/temperature.csv", header = TRUE, sep = ",", fileEncoding = "UTF-8-BOM", stringsAsFactors = FALSE))

temperature_data$Day <- mdy(temperature_data$Day)
temperature_data$Average_T <- as.numeric(temperature_data$Average_T)
temperature_data$Max_T <- as.numeric(temperature_data$Max_T)
temperature_data$Min_T <- as.numeric(temperature_data$Min_T)

temp_days <- temperature_data %>% select(Day, Average_T, Max_T, Min_T)



```





```{r, quick_plot, echo = FALSE, warning = FALSE, message = FALSE}

figs_all %>% ggplot() + geom_col(aes(x = Day, y = Combined), color = "darkgreen", fill = "darkgreen", width = 1) + scale_y_continuous(name = "Count") + ggtitle("Home Fig Tree Production Records")

solar_data %>% ggplot() + geom_smooth(aes(x = Day, y = Energy_Produced_Wh), color = "orange") + scale_y_continuous(name = "Watt-Hours") + ggtitle("Home Solar Panel Energy Production Records")

rain_days %>% ggplot() + geom_point(aes(x = Day, y = Rain), color = 'lightblue') + scale_y_continuous(name = "Inches") + ggtitle("San Diego Rain Records") + geom_vline(xintercept = ymd("2015-07-01", "2016-07-01", "2017-07-01", "2018-07-01", "2019-07-01")) + geom_text(aes(x = ymd("2015-12-30"), y = 2.5, label = "July 1 Vertical Lines"), size = 3)

temp_days %>% ggplot() + geom_smooth(aes(x = Day, y = Average_T), color = "red", span = 0.2, se = FALSE) + geom_point(aes(x = Day, y = Average_T), alpha = 0.1) + scale_y_continuous(name = "°F") + ggtitle("Carlsbad Average Temperature Records")


```



```{r, overall, echo = FALSE, warning = FALSE, message = FALSE}

#Currently dropping some fig values when merging the datasets
overall <- merge(figs_all, solar_data, by.x = "Day", by.y = "Day", all.x = TRUE)
overall <- merge(overall, daily_weather, by.x = "Day", by.y = "Day", all.x = TRUE)
overall <- merge(overall, rain_days, by.x = "Day", by.y = "Day", all.x = TRUE)
overall <- merge(overall, temp_days, by.x = "Day", by.y = "Day", all.x = TRUE)

overall %>% ggplot(aes(x = Day)) + geom_point(aes(y = Rain), color = "lightblue") + geom_point(aes(y = Combined/20), color = "darkgreen") + geom_smooth(aes(y = Energy_Produced_Wh/22000), color = "orange") + theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) + ggtitle("Rain, Solar, and Fig Count Overview - 2017 to Present")


```


```{r, 2018_closeup, echo = FALSE, warning = FALSE, message = FALSE}

#First we will subset the data for just the values 2 weeks before the first fig, and 1 week after the last

overall_2018 <- overall %>% filter(Day > "2018-06-07" & Day < "2018-11-22")

#Next we will do some plotting 

overall_2018 %>% ggplot(aes(x = Day)) + geom_point(aes(y = Average_T/15), color = "red") + geom_line(aes(y = Cumulative/400), color = "darkgreen", size = 1) + geom_point(aes(y = Energy_Produced_Wh/20000), color = "orange") + theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) + ggtitle("2018 Season - Solar, Air Temp, Cumulative Fig Count")


```

